<a href="https://colab.research.google.com/github/FlavioAugusty/Dojo---Hype/blob/main/Desafio_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Olá! Este é o desafio relativo ao Primeiro Contato com o Google Colab.

Aqui você poderá pôr em prática os seus conhecimentos recém adquiridos. Use as células abaixo para realizar as tarefas propostas.

# Tarefa 1

"monte o seu drive"

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# Tarefa 2

Procure um Dataset que voce tenha interesse no Kaggle. Se tiver dificuldade escolha um dos abaixo:

- https://www.kaggle.com/datasets/alphiree/cardiovascular-diseases-risk-prediction-dataset
- https://www.kaggle.com/datasets/arnavsmayan/netflix-userbase-dataset
- https://www.kaggle.com/datasets/nelgiriyewithana/countries-of-the-world-2023

# Tarefa 3

importe o seu Dataset

In [2]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/dataset/Mens-Volleyball-PlusLiga-2008-2023.csv')
df.head()

,Date,Team_1,Team_2,T1_Score,T2_Score,T1_Sum,T1_BP,T1_Ratio,T1_Srv_Sum,T1_Srv_Err,...,T2_Rec_Perf,T2_Att_Sum,T2_Att_Err,T2_Att_Blk,T2_Att_Kill,T2_Att_Kill_Perc,T2_Att_Eff,T2_Blk_Sum,T2_Blk_As,Winner
0,"01.10.2022, 14:45",AZS Olsztyn,ZAKSA Kędzierzyn-Koźle,1,3,60.0,17.0,11.0,79.0,18,...,26%,88,7,7,45,51%,35%,14,11,1
1,"30.09.2022, 17:30",Jastrzębski Węgiel,GKS Katowice,3,0,51.0,17.0,27.0,77.0,15,...,20%,91,8,4,43,47%,34%,1,17,0
2,"01.10.2022, 20:30",LUK Lublin,Czarni Radom,2,3,76.0,23.0,35.0,109.0,16,...,18%,128,10,10,63,49%,33%,10,13,1
3,"02.10.2022, 14:45",Warta Zawiercie,PGE Skra Bełchatów,3,2,66.0,16.0,22.0,98.0,21,...,9%,102,9,9,56,54%,37%,7,14,0
4,"03.10.2022, 17:30",BBTS Bielsko-Biała,Cuprum Lubin,1,3,63.0,22.0,17.0,100.0,19,...,22%,109,7,8,58,53%,39%,10,10,1

# Tarefa 4

obtenha algumas medidas desse Dataframe

In [ ]:
df.shape
print('\n')
df.describe()

,T1_Score,T2_Score,T1_Sum,T1_BP,T1_Ratio,T1_Srv_Sum,T1_Srv_Ace,T1_Rec_Sum,T1_Rec_Err,T1_Att_Err,...,T2_Ratio,T2_Srv_Sum,T2_Srv_Ace,T2_Rec_Sum,T2_Rec_Err,T2_Att_Err,T2_Att_Blk,T2_Att_Kill,T2_Blk_Sum,Winner
count,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,...,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000,2639.000000
mean,2.042061,1.779841,61.737401,70.758242,10.257673,31.056461,54.813945,29.942023,28.399015,77.294051,...,9.649488,30.936718,56.054566,30.857522,28.355059,77.660856,7.697234,18.380826,8.599469,0.457749
std,1.176007,1.258043,13.114343,31.119032,11.168650,31.582861,31.011209,23.861635,15.768593,44.164512,...,11.030401,31.312134,31.217354,23.759571,15.457054,44.239893,3.284414,17.348043,3.747308,0.498306
min,0.000000,0.000000,22.000000,2.000000,-10.000000,3.000000,0.000000,1.000000,0.000000,0.000000,...,-9.000000,3.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,53.000000,53.000000,3.000000,12.000000,38.500000,14.000000,17.500000,60.000000,...,3.000000,12.000000,41.000000,15.000000,18.000000,60.000000,5.000000,8.000000,6.000000,0.000000
50%,3.000000,2.000000,62.000000,74.000000,6.000000,16.000000,63.000000,20.000000,31.000000,87.000000,...,5.000000,16.000000,64.000000,21.000000,31.000000,87.000000,7.000000,11.000000,8.000000,0.000000
75%,3.000000,3.000000,72.000000,97.000000,10.000000,25.000000,81.000000,35.000000,40.000000,111.000000,...,9.000000,24.000000,81.000000,35.000000,40.000000,112.000000,10.000000,18.000000,11.000000,1.000000
max,3.000000,3.000000,94.000000,127.000000,58.000000,121.000000,115.000000,104.000000,73.000000,161.000000,...,52.000000,121.000000,114.000000,104.000000,73.000000,178.000000,21.000000,76.000000,21.000000,1.000000

# Tarefa 5

examine o Dataframe, trate valores nulos e linhas duplicadas.

In [6]:
df.isnull().sum()

Date                0
Team_1              0
Team_2              0
T1_Score            0
T2_Score            0
T1_Sum              0
T1_BP               0
T1_Ratio            0
T1_Srv_Sum          0
T1_Srv_Err          0
T1_Srv_Ace          0
T1_Srv_Eff          0
T1_Rec_Sum          0
T1_Rec_Err          0
T1_Rec_Pos          0
T1_Rec_Perf         0
T1_Att_Sum          0
T1_Att_Err          0
T1_Att_Blk          0
T1_Att_Kill         0
T1_Att_Kill_Perc    0
T1_Att_Eff          0
T1_Blk_Sum          0
T1_Blk_As           0
T2_Sum              0
T2_BP               0
T2_Ratio            0
T2_Srv_Sum          0
T2_Srv_Err          0
T2_Srv_Ace          0
T2_Srv_Eff          0
T2_Rec_Sum          0
T2_Rec_Err          0
T2_Rec_Pos          0
T2_Rec_Perf         0
T2_Att_Sum          0
T2_Att_Err          0
T2_Att_Blk          0
T2_Att_Kill         0
T2_Att_Kill_Perc    0
T2_Att_Eff          0
T2_Blk_Sum          0
T2_Blk_As           0
Winner              0
dtype: int64

In [5]:
df.duplicated().sum()

0

# Tarefa 6

Extraia algumas colunas (Series) do Dataframe

In [7]:
serie = df['T1_Score']
serie

0       1
1       3
2       2
3       3
4       1
       ..
2634    3
2635    3
2636    3
2637    3
2638    0
Name: T1_Score, Length: 2639, dtype: int64

In [ ]:
serie[10:20]

10    3
11    0
12    3
13    0
14    3
15    3
16    3
17    1
18    3
19    3
Name: T1_Score, dtype: int64

# Tarefa 7

Obtenha algumas medidas dessas colunas (Series)

In [11]:
serie.describe()

count    2639.000000
mean        2.042061
std         1.176007
min         0.000000
25%         1.000000
50%         3.000000
75%         3.000000
max         3.000000
Name: T1_Score, dtype: float64

# Tarefa 8

Extraia linhas de um dataset baseado no valor de uma variável específica

In [22]:
dfnovo = df.loc[df['Team_1'] == 'Warta Zawiercie']
dfnovo

,Date,Team_1,Team_2,T1_Score,T2_Score,T1_Sum,T1_BP,T1_Ratio,T1_Srv_Sum,T1_Srv_Err,...,T2_Rec_Perf,T2_Att_Sum,T2_Att_Err,T2_Att_Blk,T2_Att_Kill,T2_Att_Kill_Perc,T2_Att_Eff,T2_Blk_Sum,T2_Blk_As,Winner
3,"02.10.2022, 14:45",Warta Zawiercie,PGE Skra Bełchatów,3,2,66.0,16.0,22.0,98.0,21,...,9%,102,9,9,56,54%,37%,7,14,0
18,"09.10.2022, 14:45",Warta Zawiercie,ZAKSA Kędzierzyn-Koźle,3,1,73.0,25.0,39.0,97.0,15,...,14%,108,9,8,53,49%,33%,10,15,0
33,"22.10.2022, 17:30",Warta Zawiercie,AZS Olsztyn,2,3,69.0,24.0,19.0,110.0,25,...,11%,109,10,6,55,50%,35%,11,11,1
48,"03.11.2022, 16:30",Warta Zawiercie,GKS Katowice,3,0,59.0,24.0,33.0,77.0,18,...,11%,85,5,5,38,44%,32%,5,12,0
63,"06.11.2022, 20:30",Warta Zawiercie,BBTS Bielsko-Biała,3,0,51.0,19.0,27.0,73.0,10,...,15%,76,8,4,37,48%,32%,6,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1005,"24.02.2018, 17:00",Warta Zawiercie,Cuprum Lubin,2,3,80.0,98.0,9.0,22.0,"1,80",...,21,27%,98,5,9,53,54%,7,"1,40",1
1022,"07.03.2018, 18:00",Warta Zawiercie,Chemik Bydgoszcz,3,0,57.0,73.0,7.0,14.0,"2,33",...,12,20%,72,4,7,39,54%,4,"1,33",0
1039,"19.03.2018, 18:00",Warta Zawiercie,GKS Katowice,3,0,54.0,73.0,3.0,10.0,"1,00",...,12,19%,72,8,9,27,38%,6,"2,00",0
1056,"30.03.2018, 18:00",Warta Zawiercie,Stocznia Szczecin,1,3,69.0,102.0,6.0,20.0,"1,50",...,34,41%,118,8,13,64,54%,10,"2,50",1
1073,"15.04.2018, 14:45",Warta Zawiercie,BBTS Bielsko-Biała,3,1,70.0,97.0,6.0,18.0,"1,50",...,22,27%,100,7,10,47,47%,10,"2,50",0

# Tarefa 8

Realize um agrupamento de uma coluna com a função groupby()

In [26]:
# prompt: sugestão de agrupamento

# Agrupa os dados por time e calcula a média dos pontos marcados
grouped = df.groupby('Team_1')['T1_Score'].mean()
print(grouped)

Team_1
AZS Częstochowa           1.573770
AZS Olsztyn               1.979899
Asseco Resovia            2.479452
BBTS Bielsko-Biała        1.317647
Barkom Każany Lwów        1.307692
Chemik Bydgoszcz          1.803797
Cuprum Lubin              1.973913
Czarni Radom              1.776923
GKS Katowice              1.837209
Jadar Radom               1.750000
Jastrzębski Węgiel        2.422727
LUK  Lublin               1.888889
MKS Będzin                1.431818
PGE Skra Bełchatów        2.580357
Pamapol Wielton Wieluń    1.518519
Projekt Warszawa          2.015075
Społem Kielce             1.560345
Stal Nysa                 1.738095
Stocznia Szczecin         1.687500
Trefl Gdańsk              1.970060
Warta Zawiercie           2.246753
ZAKSA Kędzierzyn-Koźle    2.539474
Ślepsk Malow Suwałki      1.682927
Name: T1_Score, dtype: float64